/**
 * Mock Auth0 Service
 * ===================
 * 
 * Simulates Auth0 authentication for demonstration purposes.
 * 
 * ⚠️ EDUCATIONAL DEMO ONLY ⚠️
 * ===========================
 * In production with real Auth0:
 * 
 * 1. You would use the Auth0 React SDK:
 *    import { useAuth0 } from '@auth0/auth0-react';
 *    const { loginWithRedirect, getAccessTokenSilently, user } = useAuth0();
 * 
 * 2. Tokens are generated by Auth0 servers, not client-side
 * 
 * 3. Private keys NEVER exist in your application
 * 
 * 4. You would redirect to Auth0's login page, not show a fake form
 * 
 * This demo generates tokens client-side to show the token structure
 * and how the widget backend verifies them. The flow would be identical
 * with real Auth0 - only the token source changes.
 */

import * as jose from 'jose';
import { AUTH_CONFIG, PRIVATE_KEY } from 'shared';
import type { TokenPair, IDTokenClaims, AccessTokenClaims, User } from 'shared';

// ===========================================
// Mock Users (would come from Auth0 in production)
// ===========================================

export interface MockUser extends User {
  password: string; // Fake password for demo login form
}

export const MOCK_USERS: MockUser[] = [
  {
    sub: 'auth0|user001',
    name: 'Alice Developer',
    email: 'alice@example.com',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    password: 'password',
  },
  {
    sub: 'auth0|user002',
    name: 'Bob Tester',
    email: 'bob@example.com',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    password: 'password',
  },
  {
    sub: 'auth0|user003',
    name: 'Charlie Admin',
    email: 'charlie@example.com',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=charlie',
    password: 'password',
  },
];

// ===========================================
// Private Key Import (One-time)
// ===========================================

let privateKeyPromise: Promise<jose.KeyLike> | null = null;

async function getPrivateKey(): Promise<jose.KeyLike> {
  if (!privateKeyPromise) {
    privateKeyPromise = jose.importPKCS8(PRIVATE_KEY, 'RS256');
  }
  return privateKeyPromise;
}

// ===========================================
// Token Generation (Simulates Auth0)
// ===========================================

/**
 * Generate Auth0-style tokens for a user.
 * 
 * ⚠️ In production, Auth0 generates these tokens.
 * We're doing it here to demonstrate the token structure.
 */
export async function generateTokens(user: User): Promise<TokenPair> {
  const now = Math.floor(Date.now() / 1000);
  const privateKey = await getPrivateKey();
  
  // ID Token - contains user profile (for client-side display)
  const idTokenPayload: Omit<IDTokenClaims, 'iat' | 'exp'> = {
    iss: AUTH_CONFIG.ISSUER,
    sub: user.sub,
    aud: AUTH_CONFIG.WIDGET_CLIENT_ID,
    name: user.name,
    email: user.email,
    picture: user.picture,
    email_verified: true,
  };
  
  // Access Token - for API authorization
  const accessTokenPayload: Omit<AccessTokenClaims, 'iat' | 'exp'> = {
    iss: AUTH_CONFIG.ISSUER,
    sub: user.sub,
    aud: AUTH_CONFIG.WIDGET_API_AUDIENCE,
    scope: AUTH_CONFIG.DEFAULT_SCOPES,
    azp: AUTH_CONFIG.WIDGET_CLIENT_ID,
  };
  
  // Sign ID Token with RS256
  const idToken = await new jose.SignJWT(idTokenPayload as jose.JWTPayload)
    .setProtectedHeader({ alg: 'RS256', typ: 'JWT', kid: AUTH_CONFIG.KEY_ID })
    .setIssuedAt(now)
    .setExpirationTime(now + AUTH_CONFIG.ID_TOKEN_EXPIRY_SECONDS)
    .sign(privateKey);
  
  // Sign Access Token with RS256
  const accessToken = await new jose.SignJWT(accessTokenPayload as jose.JWTPayload)
    .setProtectedHeader({ alg: 'RS256', typ: 'JWT', kid: AUTH_CONFIG.KEY_ID })
    .setIssuedAt(now)
    .setExpirationTime(now + AUTH_CONFIG.ACCESS_TOKEN_EXPIRY_SECONDS)
    .sign(privateKey);
  
  return {
    access_token: accessToken,
    id_token: idToken,
    token_type: 'Bearer',
    expires_in: AUTH_CONFIG.ACCESS_TOKEN_EXPIRY_SECONDS,
  };
}

// ===========================================
// Mock Authentication (Simulates Auth0 Login)
// ===========================================

export interface LoginResult {
  success: boolean;
  user?: User;
  tokens?: TokenPair;
  error?: string;
}

/**
 * Simulate Auth0 login.
 * 
 * In production with Auth0:
 * - User is redirected to Auth0's Universal Login page
 * - Auth0 authenticates the user
 * - Auth0 redirects back with an authorization code
 * - Your app exchanges the code for tokens
 * 
 * This demo skips all that and generates tokens directly.
 */
export async function mockLogin(email: string, password: string): Promise<LoginResult> {
  console.log('🔐 [Mock Auth0] Login attempt:', email);
  
  // Find user
  const user = MOCK_USERS.find(u => u.email === email);
  
  if (!user) {
    console.log('❌ [Mock Auth0] User not found');
    return { success: false, error: 'User not found' };
  }
  
  if (user.password !== password) {
    console.log('❌ [Mock Auth0] Invalid password');
    return { success: false, error: 'Invalid password' };
  }
  
  // Generate tokens (simulates Auth0's token response)
  const tokens = await generateTokens(user);
  
  console.log('✅ [Mock Auth0] Login successful');
  console.log('   User:', user.name);
  console.log('   Access Token expires in:', tokens.expires_in, 'seconds');
  
  // Return user without password
  const { password: _, ...safeUser } = user;
  
  return {
    success: true,
    user: safeUser,
    tokens,
  };
}

/**
 * Simulate Auth0 logout.
 * 
 * In production: Would clear session and optionally redirect to Auth0's logout endpoint.
 */
export function mockLogout(): void {
  console.log('👋 [Mock Auth0] Logged out');
}
